services:
  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=4003
    ports:
      - "4003:4003"